name: compile-lists

on:
  # manual
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ./.github/workflows/compile-lists.yml
      - ./config.json
      - ./exclusions.txt
  schedule:
    - cron: "17 */12 * * *"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: compile lists
        id: compile-lists
        run: |
          mkdir -p compiled
          npx @adguard/hostlist-compiler --config config.json --output compiled/hostlist.txt
          [[ -z "$(git diff --ignore-matching-lines="^! Last modified")" ]] || echo "changed=true" >> $GITHUB_OUTPUT
      - name: commit & push
        if: steps.compile-lists.outputs.changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "skip ci: auto-build"
          git push origin HEAD
